# Generated by Django 4.2.16 on 2026-09-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionSubfactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactores_eval', to='evaluaciones.evaluacion')),
                ('subfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factores.subfactor')),
            ],
            options={
                'unique_together': {('evaluacion', 'subfactor')},
            },
        ),
        migrations.CreateModel(
            name='EvaluacionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia_decisor', models.IntegerField()),
                ('alcance_elegido', models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores_eval', to='evaluaciones.evaluacion')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factores.factor')),
            ],
            options={
                'unique_together': {('evaluacion', 'factor')},
            },
        ),
    ]
