# Generated by Django 4.2.16 on 2026-09-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('importancia_sugerida', models.IntegerField()),
                ('alcance', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo'), ('Ambos', 'Ambos')], max_length=10)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='factores.dimension')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subfactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactores', to='factores.factor')),
            ],
            options={
                'ordering': ['factor', 'orden'],
            },
        ),
    ]
